### ISSUE TITLE
(1) ROS2 Apps takes way too long to start [0]

### ISSUE THREAD

**Issue by klpanagi** [robotics-4-all/device-app-manager#25]
Due to ROS2 sourcing system.
Check:
- https://github.com/ros2/ros2/issues/573
- https://answers.ros.org/question/302608/sourcing-setup-in-ros2-slow/

**Comment by klpanagi** [comment]
```
root@d77a2a0cdd77:/# time ./ros_entrypoint.sh

real    0m0.974s
user    0m0.797s
sys     0m0.187s
```

**Boom!!!** :metal: :fire:

**Comment by etsardou** [comment]
:O what changed?

**Comment by etsardou** [comment]
(should change this in tektrain as well)
